export const donneesMinerais = [
  {
    id: 'roche_carbonee',
    nom: 'Roche carbonée',
    abreviation: 'roc.carb.',
    icone: '◆',
    frequence: 40,
    prixUnitaire: 1,
    description: 'Roche sombre et friable, extrêmement commune.',
  },
  {
    id: 'poussiere_silicatee',
    nom: 'Poussière silicatée',
    abreviation: 'pou.sili.',
    icone: '·',
    frequence: 30,
    prixUnitaire: 2,
    description: 'Résidus minéraux fins, abondants dans les zones banales.',
  },
  {
    id: 'olivine',
    nom: 'Olivine',
    abreviation: 'oliv.',
    icone: '⬟',
    frequence: 20,
    prixUnitaire: 2,
    description: 'Minéral commun de teinte verdâtre.',
  },
  {
    id: 'pyroxene',
    nom: 'Pyroxène',
    abreviation: 'pyrox.',
    icone: '◈',
    frequence: 15,
    prixUnitaire: 3,
    description: 'Minéral rocheux plus rentable que les extraits de base.',
  },
  {
    id: 'fer_nickel_brut',
    nom: 'Fer-nickel brut',
    abreviation: 'fer-nick.',
    icone: '▣',
    frequence: 10,
    prixUnitaire: 4,
    description: 'Agrégat métallique dense et recherché.',
  },
  {
    id: 'cobalt_natif',
    nom: 'Cobalt natif',
    abreviation: 'cob.nat.',
    icone: '✦',
    frequence: 5,
    prixUnitaire: 6,
    description: 'Métal rare et précieux, très recherché dans les zones éloignées.',
  },
]
